
export const colors = {
  primary: {
    DEFAULT: "var(--color-primary-0)",
    0: "var(--color-primary-0)",
    10: "var(--color-primary-10)",
    20: "var(--color-primary-20)",
    30: "var(--color-primary-30)",
    40: "var(--color-primary-40)",
    50: "var(--color-primary-50)",
    60: "var(--color-primary-60)",
    70: "var(--color-primary-70)",
  },
  secondary: {
    DEFAULT: "var(--color-secondary-0)",
    0: "var(--color-secondary-0)",
    10: "var(--color-secondary-10)",
    20: "var(--color-secondary-20)",
    30: "var(--color-secondary-30)",
    40: "var(--color-secondary-40)",
    50: "var(--color-secondary-50)",
    60: "var(--color-secondary-60)",
    70: "var(--color-secondary-70)",
  },
  tertiary: {
    DEFAULT: "var(--color-tertiary-0)",
    0: "var(--color-tertiary-0)",
    10: "var(--color-tertiary-10)",
    20: "var(--color-tertiary-20)",
    30: "var(--color-tertiary-30)",
    40: "var(--color-tertiary-40)",
    50: "var(--color-tertiary-50)",
    60: "var(--color-tertiary-60)",
    70: "var(--color-tertiary-70)",
  },
  "neutral-light": {
    DEFAULT: "var(--color-neutral-light-0)",
    0: "var(--color-neutral-light-0)",
    10: "var(--color-neutral-light-10)",
    20: "var(--color-neutral-light-20)",
    30: "var(--color-neutral-light-30)",
    n10: "var(--color-neutral-light-n10)",
    n20: "var(--color-neutral-light-n20)",
    n30: "var(--color-neutral-light-n30)",
  },
  "neutral-dark": {
    DEFAULT: "var(--color-neutral-dark-0)",
    0: "var(--color-neutral-dark-0)",
    10: "var(--color-neutral-dark-10)",
    20: "var(--color-neutral-dark-20)",
    30: "var(--color-neutral-dark-30)",
    n10: "var(--color-neutral-dark-n10)",
    n20: "var(--color-neutral-dark-n20)",
    n30: "var(--color-neutral-dark-n30)",
  },
  border: {
    default: "var(--color-border-default)",
    inverse: "var(--color-border-inverse)",
    highlight: "var(--color-border-highlight)",
    subtle: "var(--color-border-subtle)",
  },
  layer: {
    canvas: "var(--color-layer-canvas)",
    surface: "var(--color-layer-surface)",
    elevated: "var(--color-layer-elevated)",
  },
  interactive: {
    "primary-default": "var(--color-interactive-primary-default)",
    "primary-press": "var(--color-interactive-primary-press)",
    "primary-select": "var(--color-interactive-primary-select)",
    "primary-caption": "var(--color-interactive-primary-caption)",
    "neutral-default": "var(--color-interactive-neutral-default)",
    "neutral-press": "var(--color-interactive-neutral-press)",
    "neutral-caption": "var(--color-interactive-neutral-caption)",
    "secondary-default": "var(--color-interactive-secondary-default)",
    "secondary-press": "var(--color-interactive-secondary-press)",
    "secondary-select": "var(--color-interactive-secondary-select)",
  },
  text: {
    DEFAULT: "var(--color-text-default)",
    highlight: "var(--color-text-highlight)",
    caption: "var(--color-text-caption)",
    inverse: "var(--color-text-inverse)",
    warning: "var(--color-text-warning)",
    caution: "var(--color-text-caution)",
  },

  // Backward-compatible aliases
  accent: "var(--color-accent)",
  "sub-text": "var(--color-sub-text)",
  warning: "var(--color-warning)",
  background: "var(--color-background)",
  "card-bg": "var(--color-card-bg)",

  "btn-cancel-bg": "var(--color-btn-cancel-bg)",
  "btn-cancel-text": "var(--color-btn-cancel-text)",
  "btn-cancel-border": "var(--color-btn-cancel-border)",

  "btn-confirm-bg": "var(--color-btn-confirm-bg)",
  "btn-confirm-text": "var(--color-btn-confirm-text)",
  "btn-confirm-border": "var(--color-btn-confirm-border)",

  "btn-delete-bg": "var(--color-btn-delete-bg)",
  "btn-delete-text": "var(--color-btn-delete-text)",
  "btn-delete-border": "var(--color-btn-delete-border)",

  "state-success": "var(--color-state-success)",
  "state-info": "var(--color-state-info)",
  "state-danger": "var(--color-state-danger)",
} as const;